### ISSUE TITLE
Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2

### ISSUE THREAD

**Issue by TylorTurner** [PluginBugs/Issues-ChestPreview#19] opened 2024-01-19 16:17 UTC
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

tylorturner

### What happened?

Console spam

### Steps to reproduce the issue

Open a chest normally

### Server version

PaperMC 1.19.4 #550

### ChestPreview Version

ChestPreview_1.0.6-r2.jar

### ProtocolLib Version

ProtocolLib 5.1.0

### LoneLibs Version

LoneLibs 1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ChestPreview/files/13991577/latest.log)

### Error (optional)

```shell
[10:12:29] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "<parameter3>.a" is null
	at chestpreview.m.e.a(SourceFile:315) ~[ChestPreview_1.0.6-r2.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at java.util.Collections$SynchronizedMap.forEach(Collections.java:2735) ~[?:?]
	at chestpreview.m.e.a(SourceFile:314) ~[ChestPreview_1.0.6-r2.jar:?]
	at chestpreview.m.e.a(SourceFile:414) ~[ChestPreview_1.0.6-r2.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.callPullMoveEvent(HopperBlockEntity.java:315) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPull(HopperBlockEntity.java:253) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.lambda$suckInItems$3(HopperBlockEntity.java:472) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.anyMatch(HopperBlockEntity.java:380) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.suckInItems(HopperBlockEntity.java:469) ~[?:?]
	at net.minecraft.world.entity.vehicle.MinecartHopper.suckInItems(MinecartHopper.java:92) ~[?:?]
	at net.minecraft.world.entity.vehicle.MinecartHopper.tick(MinecartHopper.java:85) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1210) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:926) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1546) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
[10:13:27 ERROR]: Could not pass event InventoryMoveItemEvent to ChestPreview v1.0.6-r2
java.lang.NullPointerException: null
```

**Comment by TylorTurner** [comment] 2024-01-19 17:03
Sorry was using outdated ProtocolLib
updated and still have the same issue

**Comment by LoneDev6** [comment] 2024-01-23 13:14
This will be fixed ASAP, sorry for the delay

**Comment by TylorTurner** [comment] 2024-01-27 11:34
No problem can not wait to use this plugin!

**Comment by LoneDev6** [comment] 2024-02-01 12:05
Duplicate of https://github.com/PluginBugs/Issues-ChestPreview/issues/18

**Closed as not planned by LoneDev6** 2024-02-01 12:05 UTC
Labels: type: duplicate
