### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Askarionn** [PluginBugs/Issues-ChestPreview#26] opened 2024-02-07 21:06 UTC
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

[22:02:30 WARN]: [ChestPreview] Task #266726 for ChestPreview v1.0.8 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "<parameter3>.a" is null
        at chestpreview.m.j.a(SourceFile:405) ~[ChestPreview_1.0.8.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at java.util.Collections$SynchronizedMap.forEach(Collections.java:2955) ~[?:?]
        at chestpreview.m.j.a(SourceFile:404) ~[ChestPreview_1.0.8.jar:?]
        at chestpreview.m.j.b(SourceFile:505) ~[ChestPreview_1.0.8.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1643) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1522) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps to reproduce the issue

-

### Server version

 git-Pufferfish-44 (MC: 1.20.4)

### ChestPreview Version

ChestPreview version 1.0.8

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Error (optional)

```shell
[22:02:30 WARN]: [ChestPreview] Task #266726 for ChestPreview v1.0.8 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "<parameter3>.a" is null
        at chestpreview.m.j.a(SourceFile:405) ~[ChestPreview_1.0.8.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at java.util.Collections$SynchronizedMap.forEach(Collections.java:2955) ~[?:?]
        at chestpreview.m.j.a(SourceFile:404) ~[ChestPreview_1.0.8.jar:?]
        at chestpreview.m.j.b(SourceFile:505) ~[ChestPreview_1.0.8.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1643) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1522) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by bobhenl** [comment] 2024-02-08 23:35
I can confirm
```
[03:38:14 WARN]: [ChestPreview] Task #3501585 for ChestPreview v1.0.8 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "<parameter3>.a" is null
        at chestpreview.m.j.a(SourceFile:405) ~[ChestPreview_1.0.8.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at java.util.Collections$SynchronizedMap.forEach(Collections.java:2735) ~[?:?]
        at chestpreview.m.j.a(SourceFile:404) ~[ChestPreview_1.0.8.jar:?]
        at chestpreview.m.j.b(SourceFile:505) ~[ChestPreview_1.0.8.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by LoneDev6** [comment] 2024-06-10 14:05
Duplicate of #34

**Closed as not planned by LoneDev6** 2024-06-10 14:05 UTC
Labels: type: bug, type: duplicate
