### ISSUE TITLE
Task #16576100 for ChestPreview v1.0.8 generated an exception

### ISSUE THREAD

**Issue by BronzWarq** [PluginBugs/Issues-ChestPreview#29] opened 2024-02-09 20:45 UTC
### Terms

- [X] I'm using the very latest version of ChestPreview and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ChestPreview/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sholomon

### What happened?

after install new version i got error in console

### Steps to reproduce the issue

just look on container

### Server version

This server is running SSSpigot version SSSpigot2-1.20.2-20231201-7f77c2c (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT)

### ChestPreview Version

1.0.8

### ProtocolLib Version

5.1.1

### LoneLibs Version

1.0.45

### FULL server log

https://paste.helpch.at/lapogiwaqi.less

### Error (optional)

```shell
[20:36:50] [Server thread/WARN]: [ChestPreview] Task #16576100 for ChestPreview v1.0.8 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "<parameter3>.a" is null
	at chestpreview.m.j.a(SourceFile:405) ~[ChestPreview_1.0.8.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at java.util.Collections$SynchronizedMap.forEach(Collections.java:2735) ~[?:?]
	at chestpreview.m.j.a(SourceFile:404) ~[ChestPreview_1.0.8.jar:?]
	at chestpreview.m.j.b(SourceFile:505) ~[ChestPreview_1.0.8.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:459) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[20:36:51] [Server thread/WARN]: [ChestPreview] Task #16578813 for ChestPreview v1.0.8 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "<parameter3>.a" is null
	at chestpreview.m.j.a(SourceFile:405) ~[ChestPreview_1.0.8.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at java.util.Collections$SynchronizedMap.forEach(Collections.java:2735) ~[?:?]
	at chestpreview.m.j.a(SourceFile:404) ~[ChestPreview_1.0.8.jar:?]
	at chestpreview.m.j.b(SourceFile:505) ~[ChestPreview_1.0.8.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:459) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231201-7f77c2c]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
.
```

### Other files, you can drag and drop them here to upload. (optional)

.

### Screenshots/Videos (you can drag and drop files or paste links)

.

**Comment by bobhenl** [comment] 2024-03-04 18:07
Yeah I can confirm too
```
[19:06:54 WARN]: [ChestPreview] Task #71137557 for ChestPreview v1.0.8 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "<parameter3>.a" is null
        at chestpreview.m.j.a(SourceFile:405) ~[ChestPreview_1.0.8.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at java.util.Collections$SynchronizedMap.forEach(Collections.java:2735) ~[?:?]
        at chestpreview.m.j.a(SourceFile:404) ~[ChestPreview_1.0.8.jar:?]
        at chestpreview.m.j.b(SourceFile:505) ~[ChestPreview_1.0.8.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by bobhenl** [comment] 2024-03-14 20:51
Will this get ever fixed @LoneDev6 ?

**Comment by LoneDev6** [comment] 2024-06-10 14:04
Duplicate of #34

**Closed as not planned by LoneDev6** 2024-06-10 14:04 UTC
Labels: type: duplicate
